In [8]:
import pandas as pd
import geopandas as gpd
import folium


url = 'https://gist.githubusercontent.com/Nintschi/03964299a52773bea013159206264611/raw/118d8f83aaea3be609aa6d943048274ecd96e50e/Happyness_rate.csv'
#link to data on github

url_geo = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/world-countries.json'
state_geo = gpd.read_file(url_geo)
# link to countries definitions for world map

state_data = pd.read_csv(url)
# reads the csv file from the link

In [11]:
state_data = state_data [state_data.Year.eq(2018)]
state_geo

,id,name,geometry
0,AFG,Afghanistan,"POLYGON ((61.21082 35.65007, 62.23065 35.27066..."
1,AGO,Angola,"MULTIPOLYGON (((16.32653 -5.87747, 16.57318 -6..."
2,ALB,Albania,"POLYGON ((20.59025 41.85540, 20.46317 41.51509..."
3,ARE,United Arab Emirates,"POLYGON ((51.57952 24.24550, 51.75744 24.29407..."
4,ARG,Argentina,"MULTIPOLYGON (((-65.50000 -55.20000, -66.45000..."
...,...,...,...
172,PSE,West Bank,"POLYGON ((35.54566 32.39399, 35.54525 31.78251..."
173,YEM,Yemen,"POLYGON ((53.10857 16.65105, 52.38521 16.38241..."
174,ZAF,South Africa,"POLYGON ((31.52100 -29.25739, 31.32556 -29.401..."
175,ZMB,Zambia,"POLYGON ((32.75937 -9.23060, 33.23139 -9.67672..."
176,ZWE,Zimbabwe,"POLYGON ((31.19141 -22.25151, 30.65986 -22.151..."

In [ ]:
m = folium.Map(location=[48, -102],zoom_start=2, min_zoom=2, max_bounds=True)

c = folium.Choropleth(
    geo_data=url_geo,
    name='choropleth',
    highlight = True,
    nan_fill_color = 'grey',
    data=state_data,
    columns=['Code', 'Life satisfaction in Cantril Ladder (World Happiness Report 2019)'],
    key_on='feature.id',
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Life satisfaction in Cantril Ladder in 2018'
)

c.add_to(m)

folium.LayerControl().add_to(m)

state_merged = state_geo.merge (state_data, left_on='id', right_on='Code')
NIL = folium.features.GeoJson(
    state_merged,
    control=False, 
    tooltip=folium.features.GeoJsonTooltip(
        fields=['name', 'Life satisfaction in Cantril Ladder (World Happiness Report 2019)'],
        aliases=['Name', 'Life satisfaction in 2018'],
    )
)
NIL.add_to(m)

m

In [14]:
state_merged

,id,name,geometry,Entity,Code,Year,Life satisfaction in Cantril Ladder (World Happiness Report 2019)
0,AFG,Afghanistan,"POLYGON ((61.21082 35.65007, 62.23065 35.27066...",Afghanistan,AFG,2018,2.694303
1,ALB,Albania,"POLYGON ((20.59025 41.85540, 20.46317 41.51509...",Albania,ALB,2018,5.004403
2,ARE,United Arab Emirates,"POLYGON ((51.57952 24.24550, 51.75744 24.29407...",United Arab Emirates,ARE,2018,6.603744
3,ARG,Argentina,"MULTIPOLYGON (((-65.50000 -55.20000, -66.45000...",Argentina,ARG,2018,5.792797
4,ARM,Armenia,"POLYGON ((43.58275 41.09214, 44.97248 41.24813...",Armenia,ARM,2018,5.062449
...,...,...,...,...,...,...,...
125,PSE,West Bank,"POLYGON ((35.54566 32.39399, 35.54525 31.78251...",Palestine,PSE,2018,4.553922
126,YEM,Yemen,"POLYGON ((53.10857 16.65105, 52.38521 16.38241...",Yemen,YEM,2018,3.057514
127,ZAF,South Africa,"POLYGON ((31.52100 -29.25739, 31.32556 -29.401...",South Africa,ZAF,2018,4.883922
128,ZMB,Zambia,"POLYGON ((32.75937 -9.23060, 33.23139 -9.67672...",Zambia,ZMB,2018,4.041488
129,ZWE,Zimbabwe,"POLYGON ((31.19141 -22.25151, 30.65986 -22.151...",Zimbabwe,ZWE,2018,3.616480